name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set Default Config
      run: make raspberrypi4_defconfig
      
    - name: Run Make
      run: make
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: RaspberryPi4-SDCard-Image
        path: "./output/images/sdcard.img"
